# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target ’Turing’ do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Turing

pod 'AFNetworking', '~> 3.0'
pod 'SVPullToRefresh'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'SDWebImage','~>3.8'
pod 'BaiduMapKit' #百度地图SDK
end
