source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'ITSNS' do
    pod 'BaiduMapKit' #百度地图SDK
    pod 'BmobSDK'
    pod 'AFNetworking', '~> 3.0'
    pod 'SVPullToRefresh'
    pod 'MBProgressHUD', '~> 1.0.0'
    pod 'SDWebImage', '~>3.8'
end